### ISSUE TITLE
Автоматизация Code Style

### ISSUE THREAD

**Issue by DesTincT** [regru/frontend-stage#18]
- [ ] автоматизировать приведение стилей в соответствие с настройками stylelint / csscomb

Проблемы  (см. примеры ниже):
- на многих less-конструкциях csscomb валится с ошибками
- csscomb не понимает литералы
- stylelint плохо распознает правила внутри миксинов

Возможные решения:
- дописать плагин/расширение к csscomb
- сделать отдельный форк (или найти с фиксами)
- найти решение на просторах и протестировать на блоках

# Примеры:

## 1
```less
.b-arrows-navigation {
      @bl: ~".b-arrows-navigation";
      & @{bl}__arrow {          // csscomb не понимает подстановку литерала @{bl}
            position: absolute;
            left: 12px;
            top: 50%;
            margin-top: -25px;
        }
}
```
```
$ csscomb --lint bem/blocks/b-arrows-navigation/b-arrows-navigation.less
stack:  bem/blocks/b-arrows-navigation/b-arrows-navigation.less
Please check the validity of the block starting from line #19

17 |         position: static;
18 |     }
19*|     .no-tablerelative & @{bl}__arrow-relative-wrapper {
20 |         position: relative;
21 |         height: 100%;

Gonzales PE version: 3.0.0-28
Syntax: less
CSScomb Core version: 3.0.0-3.1
```

## 2
```less
.desktop({
        padding-top: 0;
        min-width: @site-width; // тут показывает ошибку, хотя в целом - всё ок

        &_notify-browser_visible {
            padding-top: 39px;
        }
    });
```
![ivan sobolev_2017-12-03_19-36-02](https://user-images.githubusercontent.com/1612160/33526916-5366f7ee-d861-11e7-857d-b617e7a65395.png)

## 3
csscomb 4 версии валится с такими ошибками, фиксы на просторах не помогают
```
destinct$ csscomb --lint bem/blocks/b-arrows-navigation/b-arrows-navigation.less
(node:86730) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): [object Object]
(node:86730) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
